name: OPC Classic Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: Restore NuGet packages
      run: nuget restore opc_rest.sln

    - name: Add msbuild to PATH
      run: actions/setup-msbuild

    - name: Build application
      run: msbuild /p:Configuration=Release opc_rest.sln
